steps:
# Frontend steps
- name: 'gcr.io/cloud-builders/npm'
  args: ['ci']
  dir: 'frontend'
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']  # Creates frontend/dist/
  dir: 'frontend'
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['rsync', '-R', 'frontend/dist/', 'gs://expenses.fachriakbarr.com/']
  dir: '.'
    
# Backend steps
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/expenses-backend', '.']
  dir: 'backend'
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/expenses-backend']
  dir: 'backend'

#Migration steps
- id: 'Start Cloud SQL Proxy'
  name: 'gcr.io/cloud-builders/docker'
  args:
    - 'run'
    - '-d'
    - '--network=cloudbuild'
    - '--name=cloudsql-proxy'
    - 'asia.gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.10.0'
    - ${_INSTANCE_CONNECTION_NAME}
    - '--port=5432'
    - '--address=0.0.0.0'
- id: 'Check Proxy Health & Wait'
  name: 'bash'
  args:
    - '-c'
    - |
      echo "Waiting 10 seconds for proxy to initialize..."
      sleep 10
      echo "Displaying proxy logs (check for 'permission denied' or 'instance not found'):"
      docker logs cloudsql-proxy || true
- id: 'Run Database Migrations'
  name: 'golang:latest'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest
      
      migrate -path backend/cmd/migrate/migrations -database "postgres://${_DB_USER}:${_DB_PASSWORD}@cloudsql-proxy:5432/${_DB_NAME}?sslmode=disable" up
# - id: 'Stop Cloud SQL Proxy'
#   name: 'gcr.io/cloud-builders/docker'
#   args:
#     - 'stop'
#     - 'cloudsql-proxy'
#   waitFor: ['-']

# Cloud run deployment steps
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo "DB_USER=$(gcloud secrets versions access latest --secret=db-user)" >> env_secrets.env
    echo "DB_PASSWORD=$(gcloud secrets versions access latest --secret=db-password)" >> env_secrets.env
    echo "DB_NAME=$(gcloud secrets versions access latest --secret=db-name)" >> env_secrets.env
    echo "INSTANCE_CONNECTION_NAME=$(gcloud secrets versions access latest --secret=instance-connection-name)" >> env_secrets.env
    echo "ALLOWED_GOOGLE_ID=$(gcloud secrets versions access latest --secret=allowed-google-id)" >> env_secrets.env
    echo "FRONTEND_URL=$(gcloud secrets versions access latest --secret=frontend-url)" >> env_secrets.env
    echo "GOOGLE_REDIRECT_URI=$(gcloud secrets versions access latest --secret=google-redirect-uri)" >> env_secrets.env
    echo "GOAUTH_CLIENT_ID=$(gcloud secrets versions access latest --secret=goauth-client-id)" >> env_secrets.env
    echo "GOAUTH_CLIENT_SECRET=$(gcloud secrets versions access latest --secret=goauth-client-secret)" >> env_secrets.env
    echo "GOAUTH_PROJECT_ID=$(gcloud secrets versions access latest --secret=goauth-project-id)" >> env_secrets.env
    echo "JWT_SECRET=$(gcloud secrets versions access latest --secret=jwt-secret)" >> env_secrets.env
    echo "ENV=production" >> env_secrets.env
- name: 'gcr.io/cloud-builders/gcloud'
  args: 
    - 'run' 
    - 'deploy'
    - 'expenses-backend'
    - '--image=gcr.io/$PROJECT_ID/expenses-backend'
    - '--platform=managed'
    - '--region=asia-southeast1'
    - '--add-cloudsql-instances=$PROJECT_ID:asia-southeast1:expenses-db'
    - '--env-vars-file=env_secrets.env'
    - '--allow-unauthenticated'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'