steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['ci']
  dir: 'frontend'
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']  # Creates frontend/dist/
  dir: 'frontend'
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['rsync', '-R', 'frontend/dist/', 'gs://expenses.fachriakbarr.com/']
  dir: '.'
    
substitutions:
  _BUCKET: 'expenses.fachriakbarr.com'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'