steps:
# Frontend steps
- name: 'gcr.io/cloud-builders/npm'
  args: ['ci']
  dir: 'frontend'
# - name: 'gcr.io/cloud-builders/npm'
#   args: ['test', '--clearCache']
#   dir: 'frontend'
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']  # Creates frontend/dist/
  dir: 'frontend'
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['rsync', '-R', 'frontend/dist/', 'gs://expenses.fachriakbarr.com/']
  dir: '.'
    
# Backend steps
# - name: 'golang:latest'
#   args: ['go', 'test', './...']
#   dir: 'backend'
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/expenses-backend', '.']
  dir: 'backend'
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/expenses-backend']
  dir: 'backend'

# #Migration steps
# - id: 'Run Database Migrations'
#   name: 'golang:latest'
#   entrypoint: 'sh'
#   args:
#     - '-c'
#     - |
#       go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest
      
#       migrate -path backend/cmd/migrate/migrations -database "postgres://${_DB_USER}:${_DB_PASSWORD}@${_DB_CONNECTION}/${_DB_NAME}?sslmode=require&channel_binding=require&search_path=public&prefer_simple_protocol=true&binary_parameters=yes" up

# Cloud run deployment steps
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo "DB_ADDR=$(gcloud secrets versions access latest --secret=db-addr)" >> env_secrets.env
    echo "DB_USER=$(gcloud secrets versions access latest --secret=db-user)" >> env_secrets.env
    echo "DB_PASSWORD=$(gcloud secrets versions access latest --secret=db-password)" >> env_secrets.env
    echo "DB_NAME=$(gcloud secrets versions access latest --secret=db-name)" >> env_secrets.env
    echo "INSTANCE_CONNECTION_NAME=$(gcloud secrets versions access latest --secret=instance-connection-name)" >> env_secrets.env
    echo "ALLOWED_GOOGLE_ID=$(gcloud secrets versions access latest --secret=allowed-google-id)" >> env_secrets.env
    echo "FRONTEND_URL=$(gcloud secrets versions access latest --secret=frontend-url)" >> env_secrets.env
    echo "GOOGLE_REDIRECT_URI=$(gcloud secrets versions access latest --secret=google-redirect-uri)" >> env_secrets.env
    echo "GOAUTH_CLIENT_ID=$(gcloud secrets versions access latest --secret=goauth-client-id)" >> env_secrets.env
    echo "GOAUTH_CLIENT_SECRET=$(gcloud secrets versions access latest --secret=goauth-client-secret)" >> env_secrets.env
    echo "GOAUTH_PROJECT_ID=$(gcloud secrets versions access latest --secret=goauth-project-id)" >> env_secrets.env
    echo "JWT_SECRET=$(gcloud secrets versions access latest --secret=jwt-secret)" >> env_secrets.env
    echo "ENV=production" >> env_secrets.env
- name: 'gcr.io/cloud-builders/gcloud'
  args: 
    - 'run' 
    - 'deploy'
    - 'expenses-backend'
    - '--image=gcr.io/$PROJECT_ID/expenses-backend'
    - '--platform=managed'
    - '--region=asia-southeast1'
    - '--add-cloudsql-instances=$PROJECT_ID:asia-southeast1:expenses-db'
    - '--env-vars-file=env_secrets.env'
    - '--allow-unauthenticated'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
