steps:
# Frontend steps
- name: 'gcr.io/cloud-builders/npm'
  args: ['ci']
  dir: 'frontend'
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']  # Creates frontend/dist/
  dir: 'frontend'
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['rsync', '-R', 'frontend/dist/', 'gs://expenses.fachriakbarr.com/']
  dir: '.'
    
# Backend steps
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/expenses-backend', '.']
  dir: 'backend'
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/expenses-backend']
  dir: 'backend'
- name: 'gcr.io/google.com/cloudsdktool/gcloud'
  args: ['run', 'deploy', 'expenses-backend', '--image=gcr.io/$PROJECT_ID/expenses-backend', '--platform=managed', '--allow-unauthenticated']

substitutions:
  _BUCKET: 'expenses.fachriakbarr.com'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'