steps:
# Frontend steps
- name: 'gcr.io/cloud-builders/npm'
  args: ['ci']
  dir: 'frontend'
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']  # Creates frontend/dist/
  dir: 'frontend'
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['rsync', '-R', 'frontend/dist/', 'gs://expenses.fachriakbarr.com/']
  dir: '.'
    
# Backend steps
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/expenses-backend', '.']
  dir: 'backend'
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/expenses-backend']
  dir: 'backend'
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo "DB_USER=$(gcloud secrets versions access latest --secret=db-user)" >> env_secrets.env
    echo "DB_PASSWORD=$(gcloud secrets versions access latest --secret=db-password)" >> env_secrets.env
    echo "DB_NAME=$(gcloud secrets versions access latest --secret=db-name)" >> env_secrets.env
    echo "INSTANCE_CONNECTION_NAME=$(gcloud secrets versions access latest --secret=instance-connection-name)" >> env_secrets.env
    echo "ALLOWED_GOOGLE_ID=$(gcloud secrets versions access latest --secret=allowed-google-id)" >> env_secrets.env
    echo "FRONTEND_URL=$(gcloud secrets versions access latest --secret=frontend-url)" >> env_secrets.env
    echo "GOOGLE_REDIRECT_URI=$(gcloud secrets versions access latest --secret=google-redirect-uri)" >> env_secrets.env
    echo "GOAUTH_CLIENT_ID=$(gcloud secrets versions access latest --secret=goauth-client-id)" >> env_secrets.env
    echo "GOAUTH_CLIENT_SECRET=$(gcloud secrets versions access latest --secret=goauth-client-secret)" >> env_secrets.env
    echo "GOAUTH_PROJECT_ID=$(gcloud secrets versions access latest --secret=goauth-project-id)" >> env_secrets.env
    echo "JWT_SECRET=$(gcloud secrets versions access latest --secret=jwt-secret)" >> env_secrets.env
    echo "ENV=production" >> env_secrets.env
- name: 'gcr.io/cloud-builders/gcloud'
  args: 
    - 'run' 
    - 'deploy'
    - 'expenses-backend'
    - '--image=gcr.io/$PROJECT_ID/expenses-backend'
    - '--platform=managed'
    - '--region=asia-southeast1'
    - '--add-cloudsql-instances=$PROJECT_ID:asia-southeast1:expenses-db'
    - '--env-vars-file=env_secrets.env'
    - '--allow-unauthenticated'
- id: 'Start Cloud SQL Proxy'
  name: 'gcr.io/cloud-builders/docker'
  args:
    - 'run'
    - '-d' # Run in detached mode (background)
    - '--network=cloudbuild' # Use the internal Cloud Build network
    - '--name=cloudsql-proxy'
    - 'gcr.io/cloudsql-connectors/cloud-sql-proxy'
    - ${_CLOUD_SQL_INSTANCE}
    - '--port=5432'
    - '--address=127.0.0.1' # Listen only on the local interface (required for the next step)

  # Step 2: Wait for the proxy to start (prevents connection errors)
- id: 'Wait for Proxy'
  name: 'bash'
  args: ['sleep', '5']

  # Step 3: Run the database migration command.
  # We use the 'golang:latest' builder image, but you might need a custom image
  # that includes the 'migrate' binary if you compiled it yourself.
- id: 'Run Database Migrations'
  name: 'golang:latest' # Replace with a builder image containing 'migrate'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      # Install the 'migrate' CLI if it's not in the image
      go install github.com/golang-migrate/migrate/cmd/migrate@latest
      
      # Execute the migration command, connecting to the proxy at 127.0.0.1
      /root/go/bin/migrate -path file://backend/cmd/migrate/migrations -database "postgres://${_DB_USER}:${_DB_PASSWORD}@127.0.0.1:5432/${_DB_NAME}?sslmode=disable" up

  # Step 4: Stop and clean up the Cloud SQL Proxy container (Optional but recommended)
- id: 'Stop Cloud SQL Proxy'
  name: 'gcr.io/cloud-builders/docker'
  args:
    - 'stop'
    - 'cloudsql-proxy'
  # This step should run even if the migration failed, so we use `always` execution.
  waitFor: ['-']

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'