steps:
# Frontend steps
- name: 'gcr.io/cloud-builders/npm'
  args: ['ci']
  dir: 'frontend'
- name: 'gcr.io/cloud-builders/npm'
  args: ['run', 'build']  # Creates frontend/dist/
  dir: 'frontend'
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['rsync', '-R', 'frontend/dist/', 'gs://expenses.fachriakbarr.com/']
  dir: '.'
    
# Backend steps
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/expenses-backend', '.']
  dir: 'backend'
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/expenses-backend']
  dir: 'backend'
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    echo "DB_USER=$(gcloud secrets versions access latest --secret=db-user)" >> env_secrets.env
    echo "DB_PASSWORD=$(gcloud secrets versions access latest --secret=db-password)" >> env_secrets.env
    echo "DB_NAME=$(gcloud secrets versions access latest --secret=db-name)" >> env_secrets.env
    echo "INSTANCE_CONNECTION_NAME=$(gcloud secrets versions access latest --secret=instance-connection-name)" >> env_secrets.env
- name: 'gcr.io/cloud-builders/gcloud'
  args: 
    - 'run' 
    - 'deploy'
    - 'expenses-backend'
    - '--image=gcr.io/$PROJECT_ID/expenses-backend'
    - '--platform=managed'
    - '--region=asia-southeast1'
    - '--add-cloudsql-instances=$_INSTANCE_CONNECTION_NAME'
    - '--set-env-vars=$(cat env_secrets.env | tr "\n" "," | sed "s/=/=/g")'
    - '--allow-unauthenticated'

substitutions:
  _BUCKET: 'expenses.fachriakbarr.com'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'