migrate-up:
	docker compose run --rm migrate-up

migrate-down:
	docker compose run --rm migrate-down

migrate-create:
	docker compose run --rm migrate-create create -seq -ext sql -dir /migrations $(name)